### ISSUE TITLE
Mention Sachertorte?

### ISSUE THREAD

**Issue by mika** [dnsmichi/atasteofaustria#3]
[Sachertorte](https://en.wikipedia.org/wiki/Sachertorte) can be [ordered online](https://www.sacher.com/en/original-sacher-cake/), I thought you might want to know that! :)

**Comment by dnsmichi** [comment]
Oh, interesting :) I'm not really a friend of it though, that is why I left it out. Someone needs to provide Kardinalschnitten und Esterhazy, that's better ;)
